import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#7d2d00",
        background: "#f8f9ff",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "surface-tint": "#0053db",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        primary: "#004ac6",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff",
        outline: "#737686",
        "inverse-primary": "#b4c5ff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        secondary: "#495c95",
        "on-secondary-fixed": "#00174b",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#ffede6",
        "outline-variant": "#c3c6d7",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#bc4800",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-surface-variant": "#434655",
        "on-secondary-container": "#394c84",
        "surface-container": "#e5eeff",
        error: "#ba1a1a",
        surface: "#f8f9ff",
        tertiary: "#943700",
        "tertiary-fixed-dim": "#ffb596",
        "secondary-container": "#acbfff",
        "on-secondary-fixed-variant": "#31447b",
        "inverse-surface": "#213145",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
